# Generated by Django 5.2.4 on 2025-08-10 16:27

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('news', 'Новости'), ('promotions', 'Акции')], default='news', help_text='Выберите тип записи: новость или акция', max_length=20, verbose_name='Категория')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение в формате JPG, PNG или GIF', null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('localities', models.ManyToManyField(related_name='news', to='cities.locality', verbose_name='Населённые пункты')),
            ],
            options={
                'verbose_name': 'Новость / акция',
                'verbose_name_plural': 'Новости и акции',
                'ordering': ['-created_at'],
            },
        ),
    ]
