# Generated by Django 5.1.7 on 2025-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options_alter_city_slug'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cities',
            field=models.ManyToManyField(related_name='news', to='cities.locality'),
        ),
    ]
