# Generated by Django 5.1.7 on 2025-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
        ('news', '0002_news_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='cities',
        ),
        migrations.AddField(
            model_name='news',
            name='localities',
            field=models.ManyToManyField(related_name='news', to='cities.locality'),
        ),
    ]
