# Generated by Django 5.1.7 on 2025-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_prepositional',
            field=models.CharField(default=1, max_length=100, verbose_name='Название в предложном падеже'),
            preserve_default=False,
        ),
    ]
