# Generated by Django 5.1.7 on 2025-04-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_region_district_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='slug',
        ),
    ]
