# Generated by Django 5.1.7 on 2025-04-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_remove_region_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='locality',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='cities.region', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localities', to='cities.district', verbose_name='Район'),
        ),
        migrations.AlterUniqueTogether(
            name='locality',
            unique_together={('name', 'region')},
        ),
    ]
