# Generated by Django 5.1.7 on 2025-05-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
