# Generated by Django 5.1.7 on 2025-03-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Офис', 'verbose_name_plural': 'Офисы'},
        ),
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Расписание работы', 'verbose_name_plural': 'Расписания работы'},
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='hours',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='cities.locality'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='days',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье'), ('Пн-Чт', 'Пн-Чт'), ('Пн-Пт', 'Пн-Пт')], max_length=50),
        ),
    ]
