# Generated by Django 5.1.7 on 2025-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_office_options_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tariff_type', models.CharField(choices=[('internet', 'Интернет'), ('tv', 'Телевидение'), ('combo', 'Комбо')], max_length=20, verbose_name='Тип')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='Скорость (Мбит/с)')),
                ('channels', models.IntegerField(blank=True, null=True, verbose_name='Количество каналов')),
                ('price', models.IntegerField(verbose_name='Цена (руб/мес)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
