# Generated by Django 5.1.7 on 2025-04-03 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tariff_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='technology',
            field=models.CharField(blank=True, choices=[('fttx', 'FTTx'), ('pon', 'PON')], default='fttx', max_length=20, verbose_name='Технология подключения'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tariff', verbose_name='Тариф')),
            ],
        ),
    ]
