# Generated by Django 5.1.7 on 2025-04-09 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_service_remove_device_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='service_type',
        ),
    ]
