# Generated by Django 5.1.7 on 2025-04-09 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_tariff_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.service', verbose_name='Тип услуги'),
        ),
    ]
