# Generated by Django 5.1.7 on 2025-04-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tariff_service_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariff',
            old_name='service_type',
            new_name='service',
        ),
    ]
