# Generated by Django 5.1.7 on 2025-04-10 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_name_prepositional'),
        ('core', '0013_rename_service_type_tariff_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='title',
        ),
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='cities.locality', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(upload_to='office_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
