# Generated by Django 5.1.7 on 2025-04-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_office_latitude_alter_office_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='office',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота'),
        ),
    ]
