# Generated by Django 5.1.7 on 2025-04-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_office_latitude_alter_office_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=100, verbose_name='Сокращенное наименование')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('okved', models.CharField(max_length=100, verbose_name='ОКВЭД')),
                ('okpo', models.CharField(max_length=10, verbose_name='ОКПО')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('ogrn_date', models.DateField(blank=True, null=True, verbose_name='Дата ОГРН')),
                ('okfs', models.CharField(max_length=10, verbose_name='ОКФС')),
                ('okogu', models.CharField(max_length=10, verbose_name='ОКОГУ')),
                ('okopf', models.CharField(max_length=10, verbose_name='ОКОПФ')),
                ('oktmo', models.CharField(max_length=10, verbose_name='ОКТМО')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('postal_address', models.CharField(max_length=255, verbose_name='Фактический (почтовый) адрес')),
                ('phone_fax', models.CharField(max_length=100, verbose_name='Телефон-факс')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Кор/счет')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('director_name', models.CharField(max_length=255, verbose_name='Генеральный директор')),
                ('director_basis', models.CharField(max_length=255, verbose_name='Действует на основании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
