# Generated by Django 5.1.7 on 2025-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_name_prepositional'),
        ('core', '0018_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cities',
            field=models.ManyToManyField(related_name='banners', to='cities.city', verbose_name='Города'),
        ),
    ]
