# Generated by Django 5.1.7 on 2025-04-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='application',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tariff', verbose_name='Тариф'),
        ),
    ]
