# Generated by Django 5.1.7 on 2025-04-14 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_city_name_prepositional'),
        ('core', '0021_alter_application_options_remove_application_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city', verbose_name='Город'),
        ),
    ]
