# Generated by Django 5.1.7 on 2025-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_application_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/backgrounds/', verbose_name='Фоновое изображение'),
        ),
    ]
