# Generated by Django 5.1.7 on 2025-04-17 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_banner_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название канала')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_hd', models.BooleanField(default=False, verbose_name='HD качество')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='channel_logos/', verbose_name='Логотип канала')),
            ],
            options={
                'verbose_name': 'ТВ канал',
                'verbose_name_plural': 'ТВ каналы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='channels',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество каналов'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (руб/мес)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.service', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скорость (Мбит/с)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='included_channels',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='core.tvchannel', verbose_name='Включённые ТВ каналы'),
        ),
    ]
