# Generated by Django 5.1.7 on 2025-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_tvchannel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='technology',
            field=models.CharField(blank=True, choices=[('fttx', 'FTTx'), ('pon', 'PON')], max_length=20, verbose_name='Технология подключения'),
        ),
    ]
