# Generated by Django 5.1.7 on 2025-04-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tariff_hd_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
    ]
