# Generated by Django 5.1.7 on 2025-04-18 18:32

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_tariff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='core.service', verbose_name='Тип услуги'),
            preserve_default=False,
        ),
    ]
