# Generated by Django 5.1.7 on 2025-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_tariff_description_alter_tariff_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='days',
            field=models.CharField(choices=[('Пн', 'Понедельник'), ('Вт', 'Вторник'), ('Ср', 'Среда'), ('Чт', 'Четверг'), ('Пт', 'Пятница'), ('Сб', 'Суббота'), ('Вс', 'Воскресенье'), ('Сб-Вс', 'Сб-Вс'), ('Пн-Чт', 'Пн-Чт'), ('Пн-Пт', 'Пн-Пт')], max_length=50),
        ),
    ]
