# Generated by Django 5.1.7 on 2025-04-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
        ('core', '0033_alter_workschedule_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='city',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='office',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='cities',
        ),
        migrations.AddField(
            model_name='application',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.locality', verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='banner',
            name='localities',
            field=models.ManyToManyField(related_name='banners', to='cities.locality', verbose_name='Населённые пункты'),
        ),
        migrations.AddField(
            model_name='office',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.locality', verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='localities',
            field=models.ManyToManyField(related_name='tariffs', to='cities.locality', verbose_name='Населённые пункты'),
        ),
    ]
