# Generated by Django 5.1.7 on 2025-04-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bik',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='company',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Кор/счет'),
        ),
        migrations.AlterField(
            model_name='company',
            name='director_basis',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Действует на основании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Генеральный директор'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okfs',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКФС'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okogu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКОГУ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okopf',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКОПФ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okpo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='oktmo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКТМО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='okved',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКВЭД'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон-факс'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический (почтовый) адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокращенное наименование'),
        ),
    ]
