# Generated by Django 5.1.7 on 2025-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_company_bank_account_alter_company_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.SlugField(help_text="URL страницы, например '/contacts/'", max_length=255, unique=True)),
                ('title', models.CharField(help_text='SEO-заголовок (до 60 символов)', max_length=255)),
                ('description', models.TextField(help_text='SEO-описание (150-160 символов)', max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255)),
                ('robots', models.CharField(default='index, follow', help_text='Инструкции для роботов', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Изображение 1200x630 px', upload_to='meta_images/')),
            ],
            options={
                'verbose_name': 'Meta-тег',
                'verbose_name_plural': 'Meta-теги',
            },
        ),
    ]
