# Generated by Django 5.1.7 on 2025-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pagemeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemeta',
            name='image',
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description'),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph изображение 1200x630 px', upload_to='og_images/'),
        ),
        migrations.AddField(
            model_name='pagemeta',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title', max_length=200),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='page_url',
            field=models.CharField(help_text="URL страницы (например, '/about/')", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='title',
            field=models.CharField(help_text='SEO-заголовок (до 60 символов)', max_length=200),
        ),
    ]
