# Generated by Django 5.1.7 on 2025-04-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_pagemeta_image_pagemeta_og_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageMeta',
        ),
    ]
