# Generated by Django 5.1.7 on 2025-04-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_pagemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, verbose_name='Слаг'),
        ),
    ]
