# Generated by Django 5.1.7 on 2025-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
        ('core', '0040_tariff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='localities',
            field=models.ManyToManyField(blank=True, null=True, related_name='tariffs', to='cities.locality', verbose_name='Населённые пункты'),
        ),
    ]
