# Generated by Django 5.1.7 on 2025-05-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_tariff_localities'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'Роутер'), ('camera', 'Видеокамера'), ('tv_box', 'ТВ-приставка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
    ]
