# Generated by Django 5.1.7 on 2025-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
        ('core', '0043_alter_device_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('router', 'Роутер'), ('camera', 'Видеокамера'), ('tv_box', 'ТВ-приставка'), ('other', 'Другое')], max_length=20, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='devices', to='core.service', verbose_name='Типы услуги'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='localities',
            field=models.ManyToManyField(blank=True, related_name='tariffs', to='cities.locality', verbose_name='Населённые пункты'),
        ),
    ]
