# Generated by Django 5.1.7 on 2025-05-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_device_description_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
    ]
