# Generated by Django 5.1.7 on 2025-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_feedback_subject_feedback_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
