# Generated by Django 5.1.7 on 2025-05-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_alter_locality_unique_together_locality_region_and_more'),
        ('core', '0048_alter_feedback_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Тип услуги', 'verbose_name_plural': 'Типы услуг'},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='service',
            name='localities',
            field=models.ManyToManyField(blank=True, related_name='services', to='cities.locality', verbose_name='Населённые пункты'),
        ),
    ]
