# Generated by Django 5.1.7 on 2025-05-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_service_options_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
