# Generated by Django 5.1.7 on 2025-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('promo', 'Акция'), ('new', 'Новинка'), ('service', 'Услуга'), ('offer', 'Предложение')], default='promo', max_length=50, verbose_name='Тип баннера'),
        ),
    ]
