# Generated by Django 5.1.7 on 2025-05-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(blank=True, choices=[('', 'Не выбрано'), ('promo', 'Акция'), ('new', 'Новинка'), ('service', 'Услуга'), ('offer', 'Предложение')], default='', max_length=50, null=True, verbose_name='Тип баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
